CREATE TABLE IF NOT EXISTS `cms_page` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) COLLATE utf8_bin NOT NULL,
  `content` text COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=5 ;
