<?php
$title = 'Ajouter une Page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('page', array('action' => 'add')));
echo $this->form()->openTag($form);
?>
<dl class="zend_form">
    <?php echo $this->formInput($form->get('id')); ?>
    <dt><?php echo $this->formLabel($form->get('title')); ?></dt>
    <dd><?php
        echo $this->formInput($form->get('title'));
        echo $this->formElementErrors($form->get('title'));?></dd>
    <dt><?php echo $this->formLabel($form->get('content')); ?></dt>
    <dd><?php
        echo $this->formTextarea($form->get('content'));
        echo $this->formElementErrors($form->get('content'));
        ?></dd>
    <dd><?php
        echo $this->formInput($form->get('submit'));
        echo $this->formElementErrors($form->get('submit'));
        ?></dd>
</dl>
<?php echo $this->form()->closeTag($form); ?>
