<?php
$title = 'Supprimer la Page';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
 
Etes-vous sûr de vouloir supprimer la page
'<?php echo $this->escapeHtml($page['title']); ?>' ?
 
<?php
$url = $this->url('page', array('action' => 'delete', 'id'=>$this->id)); ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int)$page['id']; ?>" />
        <input type="submit" name="del" value="Oui" />
        <input type="submit" name="del" value="Non" />
    </div>
</form>
